name: streamlit1
channels:
  - defaults
dependencies:
  - jupyterlab
  - matplotlib
  - numpy
  - pip
  - pandas
  - python=3.8
  - scikit-learn
  - scipy
  - spyder
  - pip:
    - simpy
    - streamlit
